# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      mkdir -p solr-data
      sudo chown 8983:8983 solr-data  
      docker run -d -v "$PWD/solr-data:/var/solr" -p 8983:8983 --name my_solr solr:8 solr-precreate my_core
      pip3 install pysolr
      pip3 install ipython
      git clone https://github.com/prust/wikipedia-movie-data.git
    command: docker start my_solr
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8983
    onOpen: open-preview
    visibility: public
